### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by HelloMorningStar** [pieter/homebridge-miio-gateway#3]
@pieter 

sudo npm install git+https://github.com/pieter/homebridge-miio-gateway/???.git

no git file

**Comment by fuermosi777** [comment]
You can git clone and then npm link

**Comment by cosmos-elegant** [comment]
Thanks! I've give up homebridge and enjoy homeassistant. Homeassistant is very easy and powerful, I can DIY lowcost hardware with espxx.

**Comment by fuermosi777** [comment]
Really? Can you connect homeassistant with iOS Home app? If so I would like to try it too...

**Comment by HelloMorningStar** [comment]
It’s a web site, you can visit it with your any devices.
